# Proyecto ciencia de datos

## Expectativas stakeholder:
"El objetivo de esta entrega es dar inicio a la creación del tablero en Power BI, que permitirá integrar y visualizar toda la información disponible. La idea es que este tablero se convierta en una herramienta dinámica, que pueda ser alimentada continuamente en el futuro con nuevos datos que vayamos recopilando."

#### Comentarios adicionales:
"Podemos revisar pacientes con complicaciones, infecciones, sobrevida, y revisar grupos etarios.


## Insumos entregados a corte 25 de septiembre de 2025

* Cirugias_Hepaticas_consolidado.xlsx   (Higado)
* Cirugias_Pancreaticas_Consolidado.xlsx (Pancreas)
* Colecistectomias_Laparoscopicas_consolidado.xlsx  (Vesicula biliar) "extracción de la vesícula biliar mediante laparoscopia" "técnica mínimamente invasiva (no se abre el abdomen por completo, sino que se usan pequeñas incisiones y una cámara)." -- suelen ser mas comunes, 
* Otras_cirugias_consolidado.xlsx 
* Trasplante_hepático_consolidado.xlsx



## Etapa 1: Entendimiento de los datos

In [101]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns



pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 300)
np.set_printoptions(suppress=True)

In [102]:
# Lectura de los datos
df_trans_hepatico = pd.read_excel('data/Trasplante hepático consolidado - Original.xlsx')

In [103]:
# Revisión de tamaño e información del dataframe
print(df_trans_hepatico.shape)  
df_trans_hepatico.info()  
df_trans_hepatico.head(5)


(736, 285)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 736 entries, 0 to 735
Columns: 285 entries, #_Paciente to Lugar_De_Recurrencia
dtypes: datetime64[ns](1), float64(185), int64(8), object(91)
memory usage: 1.6+ MB


#_Paciente  Año_Tx  Mes_Tx#1   Fecha_Tx  Edad_Al_Tx  Sexo_Receptor  \
0           1    1988         6 1988-06-02       14.00              2   
1           2    1989         1 1989-01-02        0.91              1   
2           3    1989        10 1989-10-21       28.00              2   
3           4    1990         9 1990-09-02       27.00              2   
4           5    1990         9 1990-09-18       37.00              2   

  Código de anonimización  Fecha_nacimiento     EPS Grupo_Sanguíneo_Receptor  \
0                 TXHEP001             9999  9999.0                     9999   
1                 TXHEP002             9999  9999.0                     9999   
2                 TXHEP003             9999  9999.0                     9999   
3                 TXHEP004             9999  9999.0                     9999   
4                 TXHEP005             9999  9999.0                     9999   

  RH_Receptor  COD_Grupo_Sanguíneo_Receptor  COD_RH_Receptor  \
0        9999                        9999.0           9999.0   
1        9999                        9999.0           9999.0   
2        9999                        9999.0           9999.0   
3        9999                        9999.0           9999.0   
4        9999                        9999.0           9999.0   

  Fecha-Enlistamiento  Tiempo_En_Lista_Días  Tiempo_En_Lista_Meses  \
0                9999                  9999                 9999.0   
1                9999                  9999                 9999.0   
2                9999                  9999                 9999.0   
3                9999                  9999                 9999.0   
4                9999                  9999                 9999.0   

   Tiempo_En_Lista_Años  Causa_1_Tx_Hepático_  Causa_2_Tx_Hepático_  \
0                9999.0                  23.0                   0.0   
1                9999.0                  14.0                   0.0   
2                9999.0                  23.0                   0.0   
3                9999.0                   8.0                   0.0   
4                9999.0                   9.0                   0.0   

   Hepatocarcinoma Child_Pugh_Letra  MELD_Score  Causa_Tx_Renal  Peso_Pre_Tx  \
0              0.0             9999      9999.0          9999.0       9999.0   
1              0.0             9999      9999.0          9999.0       9999.0   
2              0.0             9999      9999.0          9999.0       9999.0   
3              0.0             9999      9999.0          9999.0       9999.0   
4              0.0                C      9999.0          9999.0       9999.0   

    BMI  Composición_Corporal Falla_Cardiaca_Pre_Tx  \
0  9999                9999.0                  9999   
1  9999                9999.0                  9999   
2  9999                9999.0                  9999   
3  9999                9999.0                  9999   
4  9999                9999.0                  9999   

  Enfermedad_Coronaria_Pre_Tx Infarto_Cardiaco_Pre_Tx  \
0                        9999                    9999   
1                        9999                    9999   
2                        9999                    9999   
3                        9999                    9999   
4                        9999                    9999   

  Diabetes_Mellitus_Pre_Tx Hipertensión_Arterial_Pre_Tx  \
0                     9999                         9999   
1                     9999                         9999   
2                     9999                         9999   
3                     9999                         9999   
4                     9999                         9999   

   Antecedente_De_Tabaquismo  Antecedente_De_Alcoholismo  \
0                     9999.0                      9999.0   
1                     9999.0                      9999.0   
2                     9999.0                      9999.0   
3                     9999.0                      9999.0   
4                     9999.0            

A partir del diccionario y al revisar el comportamiento del dataframe, podemos concluir que los valores de 9999 corresponden a datos nulos, <span style="color:red">se remplazaran con el fin de realizar un calculo mas preciso de completitud de la información </span>

In [158]:
df_trans_hepatico.replace([9999, 9999.0, '9999',999,99999,'8888.0',8888.0], np.nan, inplace=True)
df_trans_hepatico.info()  
df_trans_hepatico.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 736 entries, 0 to 735
Columns: 299 entries, #_Paciente to Causa_De_Muerte_categoria
dtypes: Int64(2), datetime64[ns](15), float64(192), int64(6), object(84)
memory usage: 1.7+ MB


#_Paciente  Año_Tx  Mes_Tx#1   Fecha_Tx  Edad_Al_Tx  Sexo_Receptor  \
0           1    1988         6 1988-06-02       14.00              2   
1           2    1989         1 1989-01-02        0.91              1   
2           3    1989        10 1989-10-21       28.00              2   
3           4    1990         9 1990-09-02       27.00              2   
4           5    1990         9 1990-09-18       37.00              2   

  Código de anonimización  Fecha_nacimiento  EPS Grupo_Sanguíneo_Receptor  \
0                 TXHEP001              NaN  NaN                      NaN   
1                 TXHEP002              NaN  NaN                      NaN   
2                 TXHEP003              NaN  NaN                      NaN   
3                 TXHEP004              NaN  NaN                      NaN   
4                 TXHEP005              NaN  NaN                      NaN   

  RH_Receptor  COD_Grupo_Sanguíneo_Receptor  COD_RH_Receptor  \
0         NaN                           NaN              NaN   
1         NaN                           NaN              NaN   
2         NaN                           NaN              NaN   
3         NaN                           NaN              NaN   
4         NaN                           NaN              NaN   

  Fecha-Enlistamiento  Tiempo_En_Lista_Días  Tiempo_En_Lista_Meses  \
0                 NaN                   NaN                    NaN   
1                 NaN                   NaN                    NaN   
2                 NaN                   NaN                    NaN   
3                 NaN                   NaN                    NaN   
4                 NaN                   NaN                    NaN   

   Tiempo_En_Lista_Años  Causa_1_Tx_Hepático_  Causa_2_Tx_Hepático_  \
0                   NaN                  23.0                   0.0   
1                   NaN                  14.0                   0.0   
2                   NaN                  23.0                   0.0   
3                   NaN                   8.0                   0.0   
4                   NaN                   9.0                   0.0   

   Hepatocarcinoma Child_Pugh_Letra  MELD_Score  Causa_Tx_Renal  Peso_Pre_Tx  \
0              0.0              NaN         NaN             NaN          NaN   
1              0.0              NaN         NaN             NaN          NaN   
2              0.0              NaN         NaN             NaN          NaN   
3              0.0              NaN         NaN             NaN          NaN   
4              0.0                C         NaN             NaN          NaN   

   BMI  Composición_Corporal Falla_Cardiaca_Pre_Tx  \
0  NaN                   NaN                   NaN   
1  NaN                   NaN                   NaN   
2  NaN                   NaN                   NaN   
3  NaN                   NaN                   NaN   
4  NaN                   NaN                   NaN   

  Enfermedad_Coronaria_Pre_Tx Infarto_Cardiaco_Pre_Tx  \
0                         NaN                     NaN   
1                         NaN                     NaN   
2                         NaN                     NaN   
3                         NaN                     NaN   
4                         NaN                     NaN   

  Diabetes_Mellitus_Pre_Tx Hipertensión_Arterial_Pre_Tx  \
0                      NaN                          NaN   
1                      NaN                          NaN   
2                      NaN                          NaN   
3                      NaN                          NaN   
4                      NaN                          NaN   

   Antecedente_De_Tabaquismo  Antecedente_De_Alcoholismo  \
0                        NaN                         NaN   
1                        NaN                         NaN   
2                        NaN                         NaN   
3                        NaN                         NaN   
4                        NaN                         NaN   

  C

### Dado que tenemos muchas variables, para facilitar el entendimiento de los datos a cada variable se le da una categoria.

In [105]:
# Diccionario de categorías

cols = df_trans_hepatico.columns.tolist()
df_vars = pd.DataFrame({'Variable': cols})

categorias = {
    'Identificación del paciente': ['#_Paciente',	'Edad_Al_Tx',	'Sexo_Receptor',
    'Código de anonimización ',	'Fecha_nacimiento',	'EPS',	'Grupo_Sanguíneo_Receptor',	'RH_Receptor',	
    'COD_Grupo_Sanguíneo_Receptor',	'COD_RH_Receptor',	'Fecha-Enlistamiento',
    'Tiempo_En_Lista_Días',	'Tiempo_En_Lista_Meses',	'Tiempo_En_Lista_Años',	
    'BMI',	'Composición_Corporal',	'Enfermedad_Coronaria_Pre_Tx',	
    'Edad_Donante_Tx#1',	'Sexo_Donante_Tx#1',	'Edad_Donante_Tx#2',
    'Sexo_Donante_Tx#2',	'Edad_Donante_Tx#3',	'Sexo_Donante_Tx#3'
    ],

    'Trasplante y cirugía': ['Año_Tx',	'Mes_Tx#1',	'Fecha_Tx',	'Causa_1_Tx_Hepático_',
    'Causa_2_Tx_Hepático_',	'Causa_Tx_Renal',	'Peso_Pre_Tx',	'Falla_Cardiaca_Pre_Tx',	
    'Infarto_Cardiaco_Pre_Tx',	'Diabetes_Mellitus_Pre_Tx',	'Hipertensión_Arterial_Pre_Tx',	
    'Colesterol_TotalPre_Tx',	'LDL_Pre_Tx',	'HDL_Pre_Tx',	'Triglicéridos_Pre_Tx',	
    'Dislipidemia_Pre_Tx',	'MDRD_Score_Pre_Tx',	'MDRD_Categórico_PreTx',	
    'Valvulopatía_Pre_Tx',	'Tx#1',	'Causa_Muerte_Donante_Tx#1',	'CMV_Donante_Tx#1',
    'Cirujano_Rescate_1_Tx#1',	'Cirujano_Rescate_2_Tx#1',	'Tipo_de_Cx-Trasplante_Tx#1',	
    'Trasplante_Combinado-Hígado-Riñón_Tx#1',	'Tiempo_Isquemia_Fría_Tx#1',	
    'Tiempo_Isquemia_Caliente_Tx#1',	'Arterialización_Portal',	'Injerto_Aórtico_Tx#1',	
    '#_Unidades_Glóbulos_Rojos_Tx#1',	'#_Unidades_Plasma_Fresco_Congelado_Tx#1',	
    '#_Unidades_Crioprecipitados_Tx#1',	'#_Unidades_Plaquetas_Tx#1',	
    'Tiempo_Quirúrgico_Tx#1',	'Antibiótico_Profiláctico_VS_Terapéutico',	
    'Días_Tratamiento_Antibiótico_Previo_A_Tx#1',	'Antibiótico_1__Tx#1',	'Antibiótico_2_Tx#1',	
    'Antibiótico_3_Tx#1',	'Antifúngico_Tx#1',	'Tiempo_De_Dosis_Hasta_Tx#1',	'Cirujano_Principal_Tx#1',	
    'Cirujano_Ayudante_Tx#1',	'Fecha_Colocación_Sonda_Vesical',	'Fecha_Colocación_CVC',	
    'Soporte_Vasopresor_PeriTx',	'Levosimendan_PeriTx ',	'Levosimendam_Dosis',	
    'Noradrenalina_PeriTx',	'Noradrenalina_Dosis',	'Adrenalina_PeriTx',	
    'Vasopresina_PeriTx',	'Vasopresina_Dosis',	'Dopamina_PeriTx',	'Dopamina_Dosis',	
    'Amiodarona_PeriTx',	'Amiodarona_Dosis',	'Tx_Soporte_Inotrópico',	
    'Retrasplante',	'Indicación_Retrasplante',	'Fecha-Enlistamiento_Tx#2',	
    'Año_Tx2 (si no retx, poner año tx)',	'Fecha_Tx#2',	'Mes_Tx#2',	'Días_Reenlistado_Tx#2',	
    'Días_Desde_Tx#1',	'Causa_Muerte_Donante_Tx#2',	'CMV_Donante_Tx#0',	'Cirujano_Rescate_1_Tx#2',	
    'Cirujano_Rescate_2_Tx#2',	'Tipo_de_Cx-Trasplante_Tx#2',	'Tiempo_Isquemia_Fría_Tx#2',	'Tiempo_Isquemia_Caliente_Tx#2',	
    'Injerto_Aórtico_Tx#2',	'#_Unidades_Glóbulos_Rojos_Tx#2',	'#_Unidades_Plasma_Fresco_Congelado_Tx#2',	
    '#_Unidades_Crioprecipitados_Tx#2',	'#_Unidades_Plaquetas_Tx#2',	'Tiempo_Quirúrgico_Tx#2',	
    'Días_Tratamiento_Antibiótico_Previo_A_Tx#2',	'Antibiótico_1_Tx#2',	'Antibiótico_2_Tx#2',	
    'Antibiótico_3_Tx#2',	'Antifúngico_Tx#2',	'Segunda_Dosis_Tx#2',	'Tiempo_De_Dosis_Hasta_Tx#2',	
    'Cirujano_Principal_Tx#2',	'Cirujano_Ayudante_Tx#2',	'Re_Re trasplante',	'Indicación_Re_Re_trasplante',	
    'Fecha-Enlistamiento_Tx#3',	'Año_Tx#3',	'Fecha_Tx#3',	'Mes_Tx#3',	'Días_Reenlistado_Tx#3',	'Días_Desde_Tx#1',	'Causa_Muerte_Donante_Tx#3',	
    'CMV_Donante_Tx#3',	'Cirujano_Rescate_1_Tx#3',	'Cirujano_Rescate_2_Tx#3',	'Tipo_de_Cx-Trasplante_Tx#3',	'Tiempo_Isquemia_Fría_Tx#3',	'Tiempo_Isquemia_Caliente_Tx#3',	
    'Injerto_Aórtico_Tx#3',	'#_Unidades_Glóbulos_Rojos_Tx#3',	'#_Unidades_Plasma_Fresco_Congelado_Tx#3',	'#_Unidades_Crioprecipitados_Tx#3',	'#_Unidades_Plaquetas_Tx#3',	
    'Tiempo_Quirúrgico_Tx#3',	'Cirujano_Principal_Tx#3',	'Cirujano_Ayudante_Tx#3',	'Años_Desde_El_Tx',	'Fecha_Tx_A_PTLD',	'Tiempo_Tx_A_PTLD',	'Neoplasia_PostTx',	'Fecha_Neoplasia_PostTx',	
    'Tiempo_Tx_A_Neoplasia_PostTx',	'Fecha_última_Terapia_Local_PreTx',	'αFP_PreTx',	'Ca-19-9_PreTx',	'Neutrófilos_PreTx',	'Plaquetas_PreTx',	'Linfocitos_PreTx',	'αFP_1m_PostTx',	
    'αFP_6m_PostTx',	'αFP_1año_PostTx'
    ],

    'Hepatocarcinoma y cáncer': ['Hepatocarcinoma',	'Hepatocarcinoma',	'αFP_Al_Dx',	'#_Nódulos_Al_Dx',	'Diámetro_Nódulo_Principal_(cm)_Al_Dx',	
    'Sumatoria_#Nódulos_y_Diámetros_Al_Dx',	'Cumple_Milán',	'Cumple_UCSF',	'Cumple_Up_To_Seven',	'Terapia_Local_1',	'Terapia_Local_2',	'#_Sesiones',	'Patrón_Histológico',
    'Grado_HCC',	'Invasión_Vascular',	'Trombosis_Porta_Tumoral',	'Invasión_Linfática',	'Invasión_Nerviosa',	'Necrosis_Tumoral',	'#Nódulos_Viables',	'Diámetro_Tumor_Viable_Más_Grande_Patología',
    'Sumatoria_Nódulos_Viables_y_Diámetro_Tumor_Más_Grande_Patología',	'Ki67',	'Mitosis',	'p53',	'αFP_Patología',	'T',	'N',	'M',	'Estadio',

    ],

    'Scores clínicos': ['Child_Pugh_Letra',	'MELD_Score',	'PREMORAL_Valor',	'PREMORAL_Categoría',	'POSTMORAL_Valor',	'POSTMORAL_Categoría',	'RETREAT_Valor',	'COMBOMORAL_Valor',	'COMBOMORAL_Categoría'
    ],

    'Comorbilidades y antecedentes': ['Antecedente_De_Tabaquismo',	'Antecedente_De_Alcoholismo',	'Ecocardiograma_PreQx_Hipertensión_Pulmonar',	'Andrenalina_Dois',	'Falla_Cardiaca_POP'
    ],

    'Evaluaciones diagnósticas': ['CMV_Receptor',	'EKG_PreQx',	'EKG_PreQx_Valor',	'Ecocardiograma_PreQx_FE%',	'Ecocardiograma_PreQx-FE_Cod',	'Ecocardiograma_PreQx_RC%',	'Ecocardiograma_PreQx_RC',	
    'Ecocardiograma_PreQxPSAP',	'Ecocardiograma_PreQx_TAPSE ',	'Ecocardiograma_PreQx_TASVE',	'Ecocardiograma_PreQx_Disfunción_Diastólica',	'METS',	'EKG_VALOR_POP',	'Ecocardiograma_POP_FE%',	
    'Ecocardiograma_POP_PASP',	'Ecocardiograma_POP_Otros',	'NLR',	'PLR'
    ],

    'Seguimiento y sobrevida': [
       'Fecha_Retiro_Sonda_Vesical',	'Tiempo_Sonda_Vesical',	'Fecha_Retiro_CVC',	'Tiempo_CVC',	'Días_de_Profilaxis_Antitrombótica',	'Días_En_Hospitalización_Piso',	'Días_Totales_Intrahospitalarios',	'Vivo_Hoy',	'Fecha_Control/Muerte',	'Sobrevida_Días',	'Sobrevida_Meses',	'Sobrevida_Años',	'Último_Análisis_De_Mortalidad',	'Causa_De_Muerte',	'Sobrevida_Injerto_#1',	'Control_Injerto_#1',	'Días_Sobrevida_Injerto_#1',	'Meses_Sobrevida_Injerto_#1',	'Años_Sobrevida_Injerto_#1',	'Sobrevida_Injerto_#2',	'Control_Injerto_#2',	'Días_Sobrevida_Injerto_#2',	'Meses_Sobrevida_Injerto_#2',	'Años_Sobrevida_Injerto_#2',	'Sobrevida_Injerto_#3',	'Control_Injerto_#3',	'Días_Sobrevida_Injerto_#3',	'Meses_Sobrevida_Injerto_#3',	'Años_Sobrevida_Injerto_#3',	'PTLD',	'Recurrencia_ HCC',	'Fecha_Recurrencia',	'Lugar_De_Recurrencia',

    ],

    'Postoperatorio y complicaciones': ['Bilirrubina_Total_POP',	'COD_ Bilirrubina_Total_POP',	'Bilirrubina_Directa_POP',	'COD_Bilirrubina_Directa',	'¿Complicación?',	'#_De_Complicaciones',	'Tipo_De_Complicación_1',
    'Inmunosupresor_1',	'Inmunosupresor_2',	'Inmunosupresión_con_Anticuerpos',	'Rechazo_Agudo',	'Severidad_Rechazo_Agudo',	'Rechazo_Crónico',	'Infección_POP',	'Tipo_Infección_1',	'Germen_1',	'Fecha_Infección_1',
    'Tiempo_Desde_Tx_Infección_1',	'Tipo_Infección_2',	'Germen_2',	'Fecha_Infección_2',	'Tiempo_Desde_Tx_Infección_2',	'Tipo_Infección_3',	'Germen_3',	'Fecha_Infección_3',	'Tiempo_Desde_Tx_Infección_3',	'Stent',
    'Requirió_Reconstrucción_Biliar',	'Fecha_Reconstrucción_Biliar',	'Tiempo_Reconstrucción_Biliar',	'Profilaxis_Antitrombótica',	'Medicamento_Antitrombótica',	'Arritmia_POP',	'Infarto_POP',	'Fast_Track',	
    'Días_En_UCI',	'Fecha_Egreso_UCI ',	'Fecha_Egreso_Hospitalario',	'Sobrevida_PeriQx_30_días_POP',	'Complicación_Asociada'
    ]
}

def clasificar_variable(var):
    for categoria, palabras in categorias.items():
        if var in palabras:
            return categoria
    return 'Otras / No clasificadas'


df_vars['Categoría'] = df_vars['Variable'].apply(clasificar_variable)

# Vista general
df_vars.groupby('Categoría').size().sort_values(ascending=False)

df_vars.to_excel('clasificacion_variables_df_trans_hepatico.xlsx', index=False)



## Etapa 2: Limpieza y enriquecimiento del dataset


### Inmunosupresión_con_Anticuerpos

In [106]:
df_trans_hepatico["Inmunosupresión_con_Anticuerpos"].value_counts()


Inmunosupresión_con_Anticuerpos
0.0    172
1.0     55
2.0      1
Name: count, dtype: int64

In [107]:
# tuvo tratamiento con anticuerpos 
df_trans_hepatico["Inmunosupresión_con_Anticuerpos"].value_counts()

def clasificar_inmunosupresion(valor):
    if pd.isna(valor):
        return np.nan
    elif valor in [1, 2]:
        return "SI"
    else:
        return "NO"

df_trans_hepatico["Tuvo_Inmunosupresión_con_Anticuerpos"] = df_trans_hepatico["Inmunosupresión_con_Anticuerpos"].apply(clasificar_inmunosupresion)

df_trans_hepatico["Tuvo_Inmunosupresión_con_Anticuerpos"].value_counts()


Tuvo_Inmunosupresión_con_Anticuerpos
NO    172
SI     56
Name: count, dtype: int64

### Fecha_Infeccion_1

In [108]:
df_trans_hepatico["Fecha_Infección_1"].value_counts()

# Reemplazar la fecha específica por NaN
df_trans_hepatico['Fecha_Infección_1'] = df_trans_hepatico['Fecha_Infección_1'].replace(
    {pd.Timestamp('1927-05-17'): np.nan, pd.Timestamp('1902-09-25'): np.nan}
)

df_trans_hepatico["Fecha_Infección_1"].describe()


count          236
unique         145
top       00:00:00
freq            91
Name: Fecha_Infección_1, dtype: object

In [109]:
df_trans_hepatico["Fecha_Tx"].describe()

count                              736
mean     2014-03-29 23:32:36.521739008
min                1988-06-02 00:00:00
25%                2009-09-17 00:00:00
50%                2014-12-03 00:00:00
75%                2019-01-16 18:00:00
max                2025-03-29 00:00:00
Name: Fecha_Tx, dtype: object

### Tiempo_Desde_Tx_Infección_1

In [110]:
# df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"].unique()
# df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"].dropna().astype(int).unique()

# Convertir ambas columnas a datetime
df_trans_hepatico["Fecha_Infección_1"] = pd.to_datetime(df_trans_hepatico["Fecha_Infección_1"], errors='coerce')
df_trans_hepatico["Fecha_Tx"] = pd.to_datetime(df_trans_hepatico["Fecha_Tx"], errors='coerce')

# Ahora sí puedes restar fechas
df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"] = (
    df_trans_hepatico["Fecha_Infección_1"] - df_trans_hepatico["Fecha_Tx"]
).dt.days

df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"] = df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"].astype("Int64")
df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"].unique()


<IntegerArray>
[<NA>,    8,   64,   21,   37,  250,  111,    4,    7,   58,    9,   22,   31,
   20,   55,  102,   14,   24,   10,   35,   28,   19,   16,    5,    3,   18,
   12,    6,   11,   13,   48,   78,    1,   38,   25,   26,   15,   17,   36,
   42,    2,   29,   23,   70,   43,   52,   74,   41,   44, -262,  -56,    0,
  173,  121,   34,   57,   72]
Length: 57, dtype: Int64

In [111]:
df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"].describe()


count        145.0
mean     20.165517
std      39.751138
min         -262.0
25%            7.0
50%           12.0
75%           24.0
max          250.0
Name: Tiempo_Desde_Tx_Infección_1, dtype: Float64

Dado que es una variable caclulada a partir de la fecha del transplante y la fecha en la que se reporta una infección, no es coherente tener valores negativos, <span style="color:red"> por lo cual se toman como valores errados y se pasan a nan </span>

In [112]:
# Convertir a float para que los nulos sean np.nan y se puedan evaluar
df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"] = df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"].astype(float)

# Reemplazar valores negativos por np.nan
df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"] = np.where(
    df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"] < 0,
    np.nan,
    df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"]
)

df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"].describe()

count    143.000000
mean      22.671329
std       31.536426
min        0.000000
25%        7.000000
50%       12.000000
75%       24.000000
max      250.000000
Name: Tiempo_Desde_Tx_Infección_1, dtype: float64

### Falla_Cardiaca_POP

In [113]:
df_trans_hepatico["Falla_Cardiaca_POP"].value_counts()

df_trans_hepatico["Falla_Cardiaca_POP_bool"] = df_trans_hepatico["Falla_Cardiaca_POP"].replace({0: False, 1: True})

df_trans_hepatico["Falla_Cardiaca_POP_bool"].value_counts()



Falla_Cardiaca_POP_bool
False    610
True      13
Name: count, dtype: int64

### Arritmia_POP

In [114]:
df_trans_hepatico[["Arritmia_POP"]].describe()
df_trans_hepatico[["Arritmia_POP"]].value_counts()


Arritmia_POP                                                                                                                                                                                                         
0                                                                                                                                                                                                                        544
1                                                                                                                                                                                                                         36
3                                                                                                                                                                                                                          8
TAQUICARDIA SINUSAL                                                                                                        

In [115]:
# Supongamos que la columna se llama 'arritmia_pop'
df_trans_hepatico['Arritmia_pop_limpia'] = df_trans_hepatico['Arritmia_POP'].astype(str).str.upper().str.strip()

def clasificar_arritmia(texto):
    if texto in ['0', 'NO', 'N/A', 'NINGUNA']:
        return 0
    # Bradiarritmias
    elif any(x in texto for x in ['BRADI', 'ASISTOLIA', 'RITMO DE ESCAPE', 'AESP', 'PARO']):
        return 3
    # Taquiarritmias ventriculares
    elif any(x in texto for x in ['VENTRICULAR', 'FV', 'FIBRILACION VENTRICULAR', 'BIGEMINISMO']):
        return 2
    # Taquiarritmias supraventriculares
    elif any(x in texto for x in ['SUPRAVENT', 'FA ', 'FIBRILACION AURICULAR', 'TAQUICARDIA SINUSAL']):
        return 1
    # Casos dudosos o combinaciones múltiples
    elif any(c in texto for c in ['+', '/', 'Y']):
        # Si menciona taqui + bradi, podría marcarse como 1 (predomina taqui) o np.nan
        return np.nan
    else:
        return np.nan

df_trans_hepatico['arritmia_pop_cod'] = df_trans_hepatico['Arritmia_pop_limpia'].apply(clasificar_arritmia)

df_trans_hepatico["arritmia_pop_cod"].value_counts()


arritmia_pop_cod
0.0    544
3.0     12
1.0      7
2.0      5
Name: count, dtype: int64

In [116]:
df_trans_hepatico['arritmia_pop_descripcion'] = df_trans_hepatico['arritmia_pop_cod'].replace({0: 'NO', 1: 'TAQUIARRITMIA SUPRAVENTRICULAR', 2: 'TAQUIARRITMIA VENTRICULAR', 3: 'BRADIARRITMIA'})
df_trans_hepatico['arritmia_pop_descripcion'].value_counts()

arritmia_pop_descripcion
NO                                544
BRADIARRITMIA                      12
TAQUIARRITMIA SUPRAVENTRICULAR      7
TAQUIARRITMIA VENTRICULAR           5
Name: count, dtype: int64

### Infarto_POP

In [117]:
#df_trans_hepatico[["Infarto_POP"]].describe()
df_trans_hepatico[["Infarto_POP"]].value_counts()

def limpiar_infarto_pop(texto):
    if pd.isna(texto):
        return np.nan
    texto = str(texto).strip().upper()
    
    if texto in ['0','0.0', 'NO', 'N/A', 'NINGUNA']:
        return 0
    elif texto in ['1', '1.0','SI', 'SÍ']:
        return 1
    else:
        return np.nan

df_trans_hepatico['Infarto_POP'] = df_trans_hepatico['Infarto_POP'].apply(limpiar_infarto_pop)

df_trans_hepatico['Infarto_POP'].value_counts(dropna=False)


Infarto_POP
0.0    621
NaN    111
1.0      4
Name: count, dtype: int64

In [118]:
df_trans_hepatico["Infarto_POP_bool"] = df_trans_hepatico["Infarto_POP"].replace({0: False, 1: True})
df_trans_hepatico["Infarto_POP_bool"].value_counts(dropna=False)

Infarto_POP_bool
False    621
NaN      111
True       4
Name: count, dtype: int64

### EKG_VALOR_POP

In [119]:
df_trans_hepatico["EKG_VALOR_POP"].describe()

count     168
unique     35
top         0
freq      119
Name: EKG_VALOR_POP, dtype: int64

In [120]:
df_trans_hepatico["EKG_VALOR_POP"].unique()
df_trans_hepatico["EKG_VALOR_POP"].value_counts()


EKG_VALOR_POP
0                                    119
TAQUICARDIA SINUSAL                    5
RITMO SINUSAL                          5
1                                      3
FA                                     2
                                    ... 
TAQUIARDIA SINUSAL                     1
INVERSION T EN VI / NORMAL             1
FIBRILACION AURICULAR PAROXISTICA      1
BLOQUEO AV III GRADO                   1
FIBRILACIÓN AURICULAR                  1
Name: count, Length: 35, dtype: int64

In [121]:

def clasificar_ekg(valor):
    if pd.isna(valor) or valor.strip() in ['999', '']:
        return np.nan
    
    v = valor.upper()
    
    # Normal
    if any(x in v for x in ['0','NORMAL', 'RITMO SINUSAL', 'SIN CAMBIOS', 'SIN ALTERACIONES']):
        return 0
    
    # QTc prolongado
    elif 'QT' in v and any(x in v for x in ['1','PROLONG', 'QTC 5']):
        return 1
    
    # Trastornos de la repolarización
    elif any(x in v for x in ['2','REPOLAR', 'ONDA T', 'LESION', 'ISQUEM', 'ALTERACION INESPECIFICA']):
        return 2
    
    # Taquiarritmias supraventriculares
    elif any(x in v for x in ['3','TAQUICARDIA SINUSAL', 'TAQUIARDIA', 'FA ', 'FIBRILACION AURIC', 'FLUTTER', 'SUPRAVENTRICULAR']):
        return 3
    
    # Taquiarritmias ventriculares
    elif any(x in v for x in ['4','TAQUICARDIA VENTRICULAR', 'FIBRILACION VENTRICULAR']):
        return 4
    
    # Bradiarritmias
    elif any(x in v for x in ['5','BRADICARD', 'ASISTOL', 'BLOQUEO AV']):
        return 5
    
    # Extrasístoles
    elif 'EXTRASIST' in v or 'BIGEMINISMO' in v or '6' in v:
        return 6
    
    # Mala progresión de onda R
    elif 'ONDA R' in v or 'PROGRESION LENTA' in v or '7' in v:
        return 7
    
    # Bloqueo de rama derecha
    elif 'BLOQUEO DE RAMA DERECHA' in v or '8'in v:
        return 8
    
    # Bloqueo de rama izquierda
    elif 'BLOQUEO DE RAMA IZQ' in v or '9' in v:
        return 9
    
    else:
        return np.nan


# Aplicar
df_trans_hepatico['EKG_VALOR_POP_1'] = df_trans_hepatico['EKG_VALOR_POP'].astype(str).apply(clasificar_ekg)

# Ver resultado
df_trans_hepatico['EKG_VALOR_POP_1'].value_counts(dropna=False)

EKG_VALOR_POP_1
NaN    577
0.0    141
3.0     13
2.0      3
5.0      1
6.0      1
Name: count, dtype: int64

In [122]:
df_trans_hepatico["EKG_VALOR_POP_categoria"] = df_trans_hepatico["EKG_VALOR_POP_1"].replace({0: 'Normal', 1: 'QTc prolongado', 2: 'Trastornos de la repolarización', 
                                                                                             3: 'Taquiarritmias supraventriculares', 4: 'Taquiarritmias ventriculares', 
                                                                                             5: 'Bradiarritmias', 6: 'Extrasístoles', 7: 'Mala progresión de onda R',
                                                                                             8: 'Bloqueo de rama derecha', 9: 'Bloqueo de rama izquierda'})

df_trans_hepatico["EKG_VALOR_POP_categoria"].value_counts()


EKG_VALOR_POP_categoria
Normal                               141
Taquiarritmias supraventriculares     13
Trastornos de la repolarización        3
Bradiarritmias                         1
Extrasístoles                          1
Name: count, dtype: int64

### Retrasplante 

In [123]:
df_trans_hepatico["Retrasplante"].value_counts()

df_trans_hepatico["Retrasplante_bool"] = df_trans_hepatico["Falla_Cardiaca_POP"].replace({0: False, 1: True})

df_trans_hepatico["Retrasplante_bool"].value_counts()


Retrasplante_bool
False    610
True      13
Name: count, dtype: int64

###  Indicación_Retrasplante
 

In [124]:
df_trans_hepatico["Indicación_Retrasplante"].value_counts()

df_trans_hepatico["Indicación_Retrasplante_categoria"] = df_trans_hepatico["Indicación_Retrasplante"].replace({1:'DISFUNCIÓN PRIMARIA DEL INJERTO', 2: 'TROMBOSIS ARTERIA HEPÁTICA', 3: 'TROMBOSIS PORTAL', 
                                                                                                     4: 'BUDD CHIARI', 5: 'COLANGIOPATIA ISQUEMICA', 6: 'HELLP'})

df_trans_hepatico["Indicación_Retrasplante_categoria"].value_counts() 


Indicación_Retrasplante_categoria
DISFUNCIÓN PRIMARIA DEL INJERTO    26
TROMBOSIS ARTERIA HEPÁTICA         11
COLANGIOPATIA ISQUEMICA             2
TROMBOSIS PORTAL                    1
BUDD CHIARI                         1
HELLP                               1
Name: count, dtype: int64

### Año_Tx2

In [125]:
df_trans_hepatico["Año_Tx2 (si no retx, poner año tx)"].value_counts()

df_trans_hepatico["Año_Tx2 (si no retx, poner año tx)"]

0      1988
1      1989
2      1989
3      1990
4      1990
       ... 
731    2025
732    2025
733    2025
734    2025
735    2025
Name: Año_Tx2 (si no retx, poner año tx), Length: 736, dtype: int64

In [126]:
df_trans_hepatico[["Fecha_Tx","Año_Tx2 (si no retx, poner año tx)","Fecha_Tx#2","Retrasplante","Indicación_Retrasplante_categoria"]].loc[df_trans_hepatico["Fecha_Tx#2"].notna() |
                                                                                                                                        ((~df_trans_hepatico["Retrasplante"].astype(str).isin(["", "0.0", "NaN", "NAT", "NO"])) &  (df_trans_hepatico["Retrasplante"].notna())) |
                                                                                                                                            df_trans_hepatico["Indicación_Retrasplante_categoria"].notnull() 
                                                                                                                                            # | df_trans_hepatico["Año_Tx2 (si no retx, poner año tx)"].notna() la variable tiene datos inconsistentes
                                                                                                                                            ] 

# # Convertir ambas columnas a datetime
# df_trans_hepatico["Fecha_Tx#2"] = pd.to_datetime(df_trans_hepatico["Fecha_Tx#2"], errors='coerce')

# df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"] = (
#     df_trans_hepatico["Fecha_Infección_1"] - df_trans_hepatico["Fecha_Tx"]
# ).dt.days

# df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"] = df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"].astype("Int64")
# df_trans_hepatico["Tiempo_Desde_Tx_Infección_1"].unique()


Fecha_Tx  Año_Tx2 (si no retx, poner año tx) Fecha_Tx#2  Retrasplante  \
34  2002-12-02                                2006 2006-06-17           1.0   
51  2004-06-29                                2004 2004-07-25           1.0   
68  2005-10-16                                2005 2005-11-02           1.0   
80  2006-07-11                                2006 2006-12-06           1.0   
152 2008-12-26                                2009 2009-01-08           1.0   
..         ...                                 ...        ...           ...   
647 2022-11-23                                2022 2022-11-24           1.0   
648 2022-12-08                                2022 2022-12-09           1.0   
654 2023-02-10                                2023 2023-07-19           1.0   
711 2024-07-17                                2024 2024-07-19           1.0   
729 2025-02-25                                2025 2025-03-04           1.0   

    Indicación_Retrasplante_categoria  
34            COLANGIOPATIA ISQUEMICA  
51         TROMBOSIS ARTERIA HEPÁTICA  
68    DISFUNCIÓN PRIMARIA DEL INJERTO  
80            COLANGIOPATIA ISQUEMICA  
152   DISFUNCIÓN PRIMARIA DEL INJERTO  
..                                ...  
647   DISFUNCIÓN PRIMARIA DEL INJERTO  
648   DISFUNCIÓN PRIMARIA DEL INJERTO  
654        TROMBOSIS ARTERIA HEPÁTICA  
711                               NaN  
729   DISFUNCIÓN PRIMARIA DEL INJERTO  

[44 rows x 5 columns]

Dado que el atributo Año_tx2 no es consistente con la variable retrasplante o indicacion retrasplante, se pensaria en ajustarla, sin embargo, la definición de la variable para los stakeholder sugiere que debe dejarse asi. 

Por lo tanto, se hará uso de las variables que presentan consistencia las cuales son Retrasplante, Indicacion_Retrasplante y Fecha_Tx#2. 

### Fecha_Tx#2

In [127]:
df_trans_hepatico["Fecha_Tx#2"].describe()

count                               44
mean     2014-11-06 09:49:05.454545408
min                2004-07-25 00:00:00
25%                2010-03-03 18:00:00
50%                2014-12-13 00:00:00
75%                2018-10-07 12:00:00
max                2025-03-04 00:00:00
Name: Fecha_Tx#2, dtype: object

In [128]:
df_trans_hepatico["Fecha_Tx#2"].unique()

<DatetimeArray>
[                'NaT', '2006-06-17 00:00:00', '2004-07-25 00:00:00',
 '2005-11-02 00:00:00', '2006-12-06 00:00:00', '2009-01-08 00:00:00',
 '2009-04-03 00:00:00', '2009-08-18 00:00:00', '2009-09-20 00:00:00',
 '2009-11-26 00:00:00', '2009-12-05 00:00:00', '2009-12-27 00:00:00',
 '2010-03-26 00:00:00', '2010-06-04 00:00:00', '2010-06-27 00:00:00',
 '2010-08-16 00:00:00', '2010-12-12 00:00:00', '2011-03-17 00:00:00',
 '2011-12-16 00:00:00', '2012-10-29 00:00:00', '2014-03-04 00:00:00',
 '2014-04-21 00:00:00', '2014-09-01 00:00:00', '2024-06-05 00:00:00',
 '2015-04-12 00:00:00', '2015-03-26 00:00:00', '2015-10-11 00:00:00',
 '2015-09-23 00:00:00', '2015-11-21 00:00:00', '2016-02-25 00:00:00',
 '2016-10-16 00:00:00', '2017-06-30 00:00:00', '2017-07-10 00:00:00',
 '2018-06-30 00:00:00', '2018-07-29 00:00:00', '2019-05-07 00:00:00',
 '2019-12-18 00:00:00', '2021-04-03 00:00:00', '2021-06-25 00:00:00',
 '2021-10-09 00:00:00', '2022-11-24 00:00:00', '2022-12-09 00:00:00',
 '20

### Días_Desde_Tx#1

In [129]:
df_trans_hepatico["Días_Desde_Tx#1"].describe()

count      42.000000
mean       45.261905
std       199.944146
min         0.000000
25%         2.000000
50%         3.000000
75%        12.500000
max      1293.000000
Name: Días_Desde_Tx#1, dtype: float64

In [130]:
df_trans_hepatico["Días_Desde_Tx#1"].unique()

array([  nan, 1293.,   26.,   17.,  148.,   13.,    4.,    5.,    2.,
          1.,    3.,   11.,   10.,    8.,   32.,   43.,   23.,    9.,
         24.,    0.,   20.,  159.,    7.])

In [131]:
# Ahora sí puedes restar fechas
df_trans_hepatico["Días_Desde_Tx#1_calculada"] = (
    df_trans_hepatico["Fecha_Tx#2"] - df_trans_hepatico["Fecha_Tx"]
).dt.days

df_trans_hepatico["Días_Desde_Tx#1_calculada"] = df_trans_hepatico["Días_Desde_Tx#1_calculada"].astype("Int64")
df_trans_hepatico["Días_Desde_Tx#1_calculada"].unique()

<IntegerArray>
[<NA>, 1293,   26,   17,  148,   13,    4,    5,    2,    1,    3,   11,   10,
    8,   32, 3530,   43,   23,    9,   24,    0,   20,  159,    7]
Length: 24, dtype: Int64

In [132]:
df_trans_hepatico[["Fecha_Tx","Fecha_Tx#2","Días_Desde_Tx#1","Días_Desde_Tx#1_calculada"]].loc[df_trans_hepatico["Días_Desde_Tx#1_calculada"].isin([44,3530])]

Fecha_Tx Fecha_Tx#2  Días_Desde_Tx#1  Días_Desde_Tx#1_calculada
363 2014-10-06 2024-06-05              NaN                       3530

In [133]:
df_trans_hepatico["Días_Desde_Tx#1_calculada"].describe()

count          44.0
mean     123.477273
std      560.630438
min             0.0
25%             2.0
50%             3.0
75%            14.0
max          3530.0
Name: Días_Desde_Tx#1_calculada, dtype: Float64

Se evidecia que el valor de la variable Días_Desde_Tx#1 tiene inconsistencias que hace que las estadisticas descriptivas varien, al ser un valor extremo el que hace falta se aumenta la media y la desviacion estandar, ademas de que se pierde un dato de un retrasplante realizado despues de 3530 dias despues del primero. 

### Re_Re transplante

In [134]:
df_trans_hepatico["Re_Re trasplante"].value_counts()

Re_Re trasplante
0.0    729
1.0      2
Name: count, dtype: int64

In [135]:
df_trans_hepatico[["Fecha_Tx","Fecha_Tx#2","Días_Desde_Tx#1","Días_Desde_Tx#1_calculada","Re_Re trasplante"]].loc[df_trans_hepatico["Fecha_Tx#2"].notna() ]

Fecha_Tx Fecha_Tx#2  Días_Desde_Tx#1  Días_Desde_Tx#1_calculada  \
34  2002-12-02 2006-06-17           1293.0                       1293   
51  2004-06-29 2004-07-25             26.0                         26   
68  2005-10-16 2005-11-02             17.0                         17   
80  2006-07-11 2006-12-06            148.0                        148   
152 2008-12-26 2009-01-08             13.0                         13   
..         ...        ...              ...                        ...   
647 2022-11-23 2022-11-24              1.0                          1   
648 2022-12-08 2022-12-09              1.0                          1   
654 2023-02-10 2023-07-19            159.0                        159   
711 2024-07-17 2024-07-19              NaN                          2   
729 2025-02-25 2025-03-04              7.0                          7   

     Re_Re trasplante  
34                0.0  
51                0.0  
68                0.0  
80                0.0  
152               0.0  
..                ...  
647               1.0  
648               0.0  
654               0.0  
711               0.0  
729               0.0  

[44 rows x 5 columns]

Dada la definición del stakeholder para esta variable en donde "Re_Re Trasplante" : DEFINE SI EL PACIENTE REQUIRIÓ RE-RETRASPLANTE TEMPRANO (< 1AÑO), se evidencia que tiene inconsistencias, por lo que se procede a calcularla en funcon de Dias_Desde_Tx#1_calculada.

In [136]:
# Convertir a float para que los nulos sean np.nan y se puedan evaluar
dias = df_trans_hepatico["Días_Desde_Tx#1_calculada"].astype(float)

# Aplicar la lógica con np.where
df_trans_hepatico["Re_Re trasplante"] = np.where(
    dias < 366,
    True,
    np.where(dias.isna(), np.nan, False)
)

df_trans_hepatico["Re_Re trasplante"].value_counts()

Re_Re trasplante
1.0    42
0.0     2
Name: count, dtype: int64

### Sobrevida_PeriQx_30_días_POP

In [137]:
df_trans_hepatico["Sobrevida_PeriQx_30_días_POP"].value_counts()

Sobrevida_PeriQx_30_días_POP
1.0    646
0.0     56
Name: count, dtype: int64

### Vivo_hoy 
Variable actualizada el 05/01/2022

In [138]:
df_trans_hepatico["Vivo_Hoy"].value_counts()

Vivo_Hoy
1.0    454
0.0    248
Name: count, dtype: int64

In [139]:
df_trans_hepatico[["Edad_Al_Tx","Sexo_Receptor", "Año_Tx", "Vivo_Hoy","Fecha_Control/Muerte","Sobrevida_Días","Sobrevida_Meses","Sobrevida_Años", "Sobrevida_PeriQx_30_días_POP","Causa_De_Muerte"]].loc[
    (df_trans_hepatico["Vivo_Hoy"].isna() &
    (df_trans_hepatico["Fecha_Control/Muerte"].notna()))  
    ] 

df_trans_hepatico[["Edad_Al_Tx","Sexo_Receptor", "Año_Tx", "Vivo_Hoy","Fecha_Control/Muerte","Sobrevida_Días","Sobrevida_Meses","Sobrevida_Años", "Sobrevida_PeriQx_30_días_POP","Causa_De_Muerte"]].loc[
    (df_trans_hepatico["Vivo_Hoy"].notna() &
    (df_trans_hepatico["Fecha_Control/Muerte"].isnull()))  
    ] 
# El atriuto "Vivo_Hoy" es consistente con la fecha de control/muerte

Empty DataFrame
Columns: [Edad_Al_Tx, Sexo_Receptor, Año_Tx, Vivo_Hoy, Fecha_Control/Muerte, Sobrevida_Días, Sobrevida_Meses, Sobrevida_Años, Sobrevida_PeriQx_30_días_POP, Causa_De_Muerte]
Index: []

### Fecha_Control/Muerte

In [140]:
df_trans_hepatico["Fecha_Control/Muerte"].describe()

count                              702
mean     2021-11-20 01:58:58.461538560
min                2002-11-29 00:00:00
25%                2020-11-14 00:00:00
50%                2024-12-31 00:00:00
75%                2024-12-31 00:00:00
max                2025-04-01 00:00:00
Name: Fecha_Control/Muerte, dtype: object

### Sobrevida_Días

In [141]:
df_trans_hepatico["Sobrevida_Días"].describe()

count      704.000000
mean      2317.992898
std       3788.853487
min     -45745.000000
25%        489.500000
50%       2347.000000
75%       4013.000000
max       8086.000000
Name: Sobrevida_Días, dtype: float64

In [142]:
df_trans_hepatico["Sobrevida_Días_calculado"] = (
    df_trans_hepatico["Fecha_Control/Muerte"] - df_trans_hepatico["Fecha_Tx"]
).dt.days

df_trans_hepatico["Sobrevida_Días_calculado"] = df_trans_hepatico["Sobrevida_Días_calculado"].astype("Int64")
df_trans_hepatico["Sobrevida_Días_calculado"].unique()

<IntegerArray>
[<NA>, 8086, 8085,    1, 8065, 2420, 7960,  308,  146, 7754,
 ...
  111,  101,   84,   76,   63,   55,   49,   43,   71,   27]
Length: 640, dtype: Int64

In [143]:
df_trans_hepatico[["Fecha_Tx","Edad_Al_Tx","Sexo_Receptor", "Año_Tx", "Vivo_Hoy","Fecha_Control/Muerte","Sobrevida_Días","Sobrevida_Días_calculado","Sobrevida_Meses","Sobrevida_Años", "Sobrevida_PeriQx_30_días_POP","Causa_De_Muerte"]].loc[df_trans_hepatico["Sobrevida_Días"]<0]

Fecha_Tx  Edad_Al_Tx  Sexo_Receptor  Año_Tx  Vivo_Hoy  \
733 2025-03-24        43.0              1    2025       NaN   
734 2025-03-27        55.0              1    2025       NaN   
735 2025-03-29        36.0              1    2025       NaN   

    Fecha_Control/Muerte  Sobrevida_Días  Sobrevida_Días_calculado  \
733                  NaT        -45740.0                      <NA>   
734                  NaT        -45743.0                      <NA>   
735                  NaT        -45745.0                      <NA>   

     Sobrevida_Meses  Sobrevida_Años  Sobrevida_PeriQx_30_días_POP  \
733     -1524.666667     -127.055556                           NaN   
734     -1524.766667     -127.063889                           NaN   
735     -1524.833333     -127.069444                           NaN   

    Causa_De_Muerte  
733             NaN  
734             NaN  
735             NaN

In [144]:
df_trans_hepatico[["Fecha_Tx","Edad_Al_Tx","Sexo_Receptor", "Año_Tx", "Vivo_Hoy","Fecha_Control/Muerte","Sobrevida_Días","Sobrevida_Días_calculado","Sobrevida_Meses","Sobrevida_Años", "Sobrevida_PeriQx_30_días_POP","Causa_De_Muerte"]].loc[
    df_trans_hepatico["Sobrevida_Días"]!= df_trans_hepatico["Sobrevida_Días_calculado"]]

Fecha_Tx  Edad_Al_Tx  Sexo_Receptor  Año_Tx  Vivo_Hoy  \
732 2025-03-05        56.0              2    2025       1.0   

    Fecha_Control/Muerte  Sobrevida_Días  Sobrevida_Días_calculado  \
732           2025-04-01            20.0                        27   

     Sobrevida_Meses  Sobrevida_Años  Sobrevida_PeriQx_30_días_POP  \
732         0.666667        0.055556                           1.0   

    Causa_De_Muerte  
732             NaN

In [145]:
df_trans_hepatico["Sobrevida_Días_calculado"].describe()

count          702.0
mean     2521.511396
std      2114.754796
min              0.0
25%            499.0
50%           2350.5
75%           4013.0
max           8086.0
Name: Sobrevida_Días_calculado, dtype: Float64

<span style="color:red">Se sugiere trabajar con el dato calculado dado que se encuentra una inconsistencia en el dato capturado </span>

### Causa_De_Muerte

In [146]:
pd.set_option('display.max_rows', 100)
df_trans_hepatico["Causa_De_Muerte"].value_counts()

# 1: COAGULOPATÍA 
# 2: SEPSIS
# 3: EMBOLIA PULMONAR
# 4: RECHAZO CRÓNICO
# 5: OBSTRUCCION DE LA VIA AEREA
# 6: BRONCOASPIRACION 
# 7: COLANGIOCARCINOMA
# 8: NEUROLOGICA
# 9: HEMORRAGIA SUBARACNOIDEA
# 10: ENCEFALITIS HERPES
# 11: NEUMONIA
# 12: FALLA MULTIORGANICA
# 13: MUERTE IO
# 14: ANGIOSARCOMA
# 15: HCC
# 16: SHOCK HIPOVOLEMICO
# 17: ASPERGILOSIS
# 18: DISFUNCIÓN HEPÁTICA
# 19: ISQUEMIA MESENTÉRICA
# 20: EDEMA PULMONAR
# 21: FALLA VENTILATORIA
# 22: ILEO ADINÁMICO
# 23: RECURRENCIA HCV
# 24: ONCOLÓGICO
# 

Causa_De_Muerte
2                                 25
12                                15
18                                10
1                                  8
FALLA MULTI                        5
13                                 4
4                                  4
8                                  3
11                                 3
16                                 3
5                                  3
hiporexia                          2
6                                  2
SHOCK SEPTICO/DISFUNCION           2
24                                 2
17                                 2
shock                              1
25                                 1
shock mixto                        1
enceladopatia hipoxia              1
sepsis abdominal                   1
SEPSIS GI                          1
****                               1
FALLA RENAL AGUDA                  1
Insifuciencia renal aguda          1
23                                 1
19                    

In [147]:
def clasificar_causa_muerte(texto):
    if pd.isna(texto):
        return np.nan

    texto = str(texto).upper().strip()

    # Mapeo directo por número
    if texto.isdigit():
        num = int(texto)
        if num in range(1, 25):
            return num

    # Reglas por texto libre
    elif any(x in texto for x in ['FALLA MULTI', 'MULTIORGAN']):
        return 12  # FALLA MULTIORGÁNICA
    elif 'SEPSIS' in texto:
        return 2   # SEPSIS
    elif any(x in texto for x in ['EMBOL', 'TROMBOSIS']):
        return 3   # EMBOLIA PULMONAR
    elif 'RECHAZO' in texto:
        return 4   # RECHAZO CRÓNICO
    elif any(x in texto for x in ['AEREA', 'OBSTRUCCION']):
        return 5   # OBSTRUCCIÓN DE LA VÍA AÉREA
    elif 'BRONCOASP' in texto:
        return 6   # BRONCOASPIRACIÓN
    elif 'COLANGIO' in texto:
        return 7   # COLANGIOCARCINOMA
    elif any(x in texto for x in ['NEURO', 'ENCEFAL', 'CEREBR']):
        return 8   # NEUROLÓGICA
    elif 'SUBARACNO' in texto:
        return 9   # HEMORRAGIA SUBARACNOIDEA
    elif 'HERPES' in texto:
        return 10  # ENCEFALITIS HERPES
    elif any(x in texto for x in ['NEUMON', 'COVID']):
        return 11  # NEUMONÍA
    elif any(x in texto for x in ['DISFUNCION', 'DISFUNCIÓN', 'HEPAT']):
        return 18  # DISFUNCIÓN HEPÁTICA
    elif 'ANGIOSARCOMA' in texto:
        return 14  # ANGIOSARCOMA
    elif 'HCC' in texto:
        return 15  # HCC
    elif any(x in texto for x in ['SHOCK', 'CHOQUE']):
        return 16  # SHOCK HIPOVOLÉMICO
    elif 'ASPERG' in texto:
        return 17  # ASPERGILOSIS
    elif 'ISQUEMIA' in texto:
        return 19  # ISQUEMIA MESENTÉRICA
    elif 'EDEMA' in texto:
        return 20  # EDEMA PULMONAR
    elif 'VENTILATOR' in texto:
        return 21  # FALLA VENTILATORIA
    elif 'ILEO' in texto:
        return 22  # ÍLEO ADINÁMICO
    elif 'HCV' in texto:
        return 23  # RECURRENCIA HCV
    elif 'ONCOL' in texto:
        return 24  # ONCOLÓGICO
    elif any(x in texto for x in ['RENAL', 'HIPOREXIA']):
        return 12  # FALLA MULTIORGÁNICA (asociado)
    else:
        return np.nan


# Aplicación sobre tu DataFrame
df_trans_hepatico["Causa_De_Muerte_cod"] = df_trans_hepatico["Causa_De_Muerte"].apply(clasificar_causa_muerte)
df_trans_hepatico["Causa_De_Muerte_cod"].loc[~df_trans_hepatico["Causa_De_Muerte_cod"].isnull()].value_counts()

Causa_De_Muerte_cod
2.0     28
12.0    24
18.0    12
1.0      8
16.0     6
11.0     4
8.0      4
13.0     4
4.0      4
5.0      3
17.0     2
3.0      2
21.0     2
24.0     2
6.0      2
15.0     1
19.0     1
7.0      1
20.0     1
22.0     1
23.0     1
Name: count, dtype: int64

In [148]:
catalogo = {
    1: "COAGULOPATÍA", 2: "SEPSIS", 3: "EMBOLIA PULMONAR", 4: "RECHAZO CRÓNICO", 
    5: "OBSTRUCCIÓN DE LA VÍA AÉREA", 6: "BRONCOASPIRACIÓN", 7: "COLANGIOCARCINOMA", 
    8: "NEUROLÓGICA", 9: "HEMORRAGIA SUBARACNOIDEA", 10: "ENCEFALITIS HERPES", 
    11: "NEUMONÍA", 12: "FALLA MULTIORGÁNICA", 13: "MUERTE IO", 14: "ANGIOSARCOMA", 
    15: "HCC", 16: "SHOCK HIPOVOLÉMICO", 17: "ASPERGILOSIS", 18: "DISFUNCIÓN HEPÁTICA", 
    19: "ISQUEMIA MESENTÉRICA", 20: "EDEMA PULMONAR", 21: "FALLA VENTILATORIA", 
    22: "ÍLEO ADINÁMICO", 23: "RECURRENCIA HCV", 24: "ONCOLÓGICO"
}

df_trans_hepatico['Causa_De_Muerte_categoria'] = df_trans_hepatico['Causa_De_Muerte_cod'].map(catalogo)

df_trans_hepatico["Causa_De_Muerte_categoria"].value_counts()

Causa_De_Muerte_categoria
SEPSIS                         28
FALLA MULTIORGÁNICA            24
DISFUNCIÓN HEPÁTICA            12
COAGULOPATÍA                    8
SHOCK HIPOVOLÉMICO              6
NEUMONÍA                        4
NEUROLÓGICA                     4
MUERTE IO                       4
RECHAZO CRÓNICO                 4
OBSTRUCCIÓN DE LA VÍA AÉREA     3
ASPERGILOSIS                    2
EMBOLIA PULMONAR                2
FALLA VENTILATORIA              2
ONCOLÓGICO                      2
BRONCOASPIRACIÓN                2
HCC                             1
ISQUEMIA MESENTÉRICA            1
COLANGIOCARCINOMA               1
EDEMA PULMONAR                  1
ÍLEO ADINÁMICO                  1
RECURRENCIA HCV                 1
Name: count, dtype: int64

### Complicación_Asociada

In [149]:
df_trans_hepatico["Complicación_Asociada"].value_counts()

Complicación_Asociada
NINGUNA                                                                                                                                                                                                                                                                                                                                                              54
4                                                                                                                                                                                                                                                                                                                                                                     8
1                                                                                                                                                                                                                                                                 

### PTLD

In [150]:
df_trans_hepatico["PTLD"].value_counts()

PTLD
0    624
1     21
       1
Name: count, dtype: int64

In [151]:
df_trans_hepatico["PTLD"].unique()
# Paso 1: convertir a string
df_trans_hepatico["PTLD"] = df_trans_hepatico["PTLD"].astype(str)

# Paso 2: conservar solo los valores que son '0' o '1', y poner NaN en el resto
df_trans_hepatico["PTLD"] = df_trans_hepatico["PTLD"].where(
    df_trans_hepatico["PTLD"].str.match(r"^[01]$"),
    np.nan
)
df_trans_hepatico["PTLD"].value_counts()

PTLD
0    624
1     21
Name: count, dtype: int64

### Tiempo_Tx_A_PTLD

In [152]:
df_trans_hepatico["Tiempo_Tx_A_PTLD"].value_counts()

Tiempo_Tx_A_PTLD
0            146
RITUXIMAB      1
1              1
Name: count, dtype: int64

In [153]:
df_trans_hepatico["Tiempo_Tx_A_PTLD"].loc[~df_trans_hepatico["Tiempo_Tx_A_PTLD"].isna()]


468    RITUXIMAB
526            0
527            0
528            0
529            0
         ...    
669            0
670            0
671            0
672            0
674            0
Name: Tiempo_Tx_A_PTLD, Length: 148, dtype: object

La variable deberia reflejar el tiempo en dias desde el transplante a la identificación de un PTLD. Parece tener un comportamiento booleano. <span style="color:red"> No es consistente </span>

### Neoplasia_PostTx

In [ ]:
df_trans_hepatico["Neoplasia_PostTx"].value_counts()

Neoplasia_PostTx
0.0    612
1.0     14
2.0      2
5.0      2
7.0      1
3.0      1
6.0      1
4.0      1
Name: count, dtype: int64

In [163]:
df_trans_hepatico["Neoplasia_PostTx"] = df_trans_hepatico["Neoplasia_PostTx"].replace({0:'NO' ,1:'PTLD', 2: 'CA PIEL', 3: 'CA PULMON', 
                                                                                                     4: 'CA UTERO', 5: 'SARCOMA DE KAPOSI', 6: 'CA RENAL',
                                                                                                     7: 'CA SENO',8:'LEUCEMIAS', 9: 'CA COLON',10 : 'LINFOMA' ,11:'COLANGIOCA',12: 'CA PROSTATA' ,13:'CA CERVIX',14:'PSEUDOMIXOMA PERITONEAL',
                                                                                                     15:'HCC',16:'ANGIOSARCOMA',17:'TX NEUROENDOCRINO',18:'CYSTADENOMA'})
df_trans_hepatico["Neoplasia_PostTx"].value_counts()

Neoplasia_PostTx
NO                   612
PTLD                  14
CA PIEL                2
SARCOMA DE KAPOSI      2
CA SENO                1
CA PULMON              1
CA RENAL               1
CA UTERO               1
Name: count, dtype: int64

### Tiempo_Tx_A_Neoplasia_PostTx

In [165]:
df_trans_hepatico["Tiempo_Tx_A_Neoplasia_PostTx"].unique()

array([nan,  0.])

La varaible no tiene datos. A pesar de que el conteo de no nulidad mostraba un 20% de completitud

### Grado_HCC

In [166]:
df_trans_hepatico["Grado_HCC"].value_counts()

Grado_HCC
2.0    49
3.0    40
4.0     6
1.0     4
Name: count, dtype: int64

In [167]:
df_trans_hepatico["Grado_HCC"].unique()

array([nan,  1.,  3.,  2.,  4.])

### Estadio

In [169]:

df_trans_hepatico.loc[
    df_trans_hepatico['Estadio'].notnull() ].value_counts('Estadio')


Estadio
1.0    53
2.0    37
3.0     8
4.0     1
Name: count, dtype: int64

In [172]:
df_trans_hepatico["Estadio"] = df_trans_hepatico["Estadio"].replace({0:'NO' ,1:'ESTADIO 1', 2: 'ESTADIO 2', 3: 'ESTADIO 3',4: 'ESTADIO 4'})
df_trans_hepatico["Estadio"].value_counts()

Estadio
ESTADIO 1    53
ESTADIO 2    37
ESTADIO 3     8
ESTADIO 4     1
Name: count, dtype: int64

In [156]:
df_trans_hepatico[['Amiodarona_Dosis','Amiodarona_PeriTx']].loc[
    df_trans_hepatico['Amiodarona_PeriTx']== 1
]


Amiodarona_Dosis  Amiodarona_PeriTx
62                                                 300                1.0
87                                                 300                1.0
120                                                150                1.0
132                                              300MG                1.0
134                           150MG STAT / 15 MG/HORA                 1.0
139  300 MG BOLO  X2Y POSTERIOR 30 MG HORA/ complet...                1.0
152                                                NaN                1.0
155                                                400                1.0
158                                                 NV                1.0
167                                   BOLO Y EINFUSION                1.0
188                                                300                1.0
194                                                150                1.0
213                                                 30                1.0
218                                                 30                1.0
220                                                150                1.0
232                                                300                1.0
235                                                300                1.0
243                                              300mg                1.0
244                                              150mg                1.0
271                                                150                1.0
379                                                300                1.0
393                                                  3                1.0
432                                                150                1.0
470                                                150                1.0
628                                                300                1.0
653                                                150                1.0
683                                                300                1.0
688                                                150                1.0

# Le daré otro enfoque a la revisión
Dado que los datos son capturados por los medicos en su rural, y esta actividad lo que hace es rescatar la mayor cantidad de datos posible, esto implica que variables con bajo porcentaje de no nulidad no deban ser no priorizados, por ello, se realizará una revisión de las variabes basado en 3 enfoques resaltados por la parte interesada que son:

* Determinar clasificación etaria y revision de variables demograficas
* Mostrar posibles determinantes de  complicaciones postquirurgicas 
* Mostrar existencia de infecciones
* Analisar sobrevida.


Las comorbilidades estan separadas en su mayoria por Y, se limpiara el dato y se obtendra el numero de comorbilidades por paciente, para determinar si tiene implicaciones en las preguntas de stakeholder como complicaciones, infecciones o supervivencia.